FROM java:openjdk-8-jdk

COPY gs-actuator-service-0.1.0.jar ./
CMD ["java", "-jar", "gs-actuator-service-0.1.0.jar"]

# CONFIGURE IMAGE
EXPOSE      9000
CMD        ["java", "-jar", "gs-actuator-service-0.1.0.jar"]