version: "2"
services:

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  npm_app:
    image: node
    links:
      - mongo
    volumes:
      - ./:/code
    working_dir: /code
    command: bash -c "npm install && npm start"
    ports:
         - "3000:3000"
